//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto copies the receiver into out.
func (in *ComponentStatus) DeepCopyInto(out *ComponentStatus) {
	*out = *in
}

// DeepCopy returns a deep copy of ComponentStatus.
func (in *ComponentStatus) DeepCopy() *ComponentStatus {
	if in == nil {
		return nil
	}
	out := new(ComponentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out.
func (in *FeaturesSpec) DeepCopyInto(out *FeaturesSpec) {
	*out = *in
}

// DeepCopy returns a deep copy of FeaturesSpec.
func (in *FeaturesSpec) DeepCopy() *FeaturesSpec {
	if in == nil {
		return nil
	}
	out := new(FeaturesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out.
func (in *IdentitySpec) DeepCopyInto(out *IdentitySpec) {
	*out = *in
}

// DeepCopy returns a deep copy of IdentitySpec.
func (in *IdentitySpec) DeepCopy() *IdentitySpec {
	if in == nil {
		return nil
	}
	out := new(IdentitySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out.
func (in *StorageSpec) DeepCopyInto(out *StorageSpec) {
	*out = *in
	out.MediaSize = in.MediaSize.DeepCopy()
}

// DeepCopy returns a deep copy of StorageSpec.
func (in *StorageSpec) DeepCopy() *StorageSpec {
	if in == nil {
		return nil
	}
	out := new(StorageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out.
func (in *UpdateSpec) DeepCopyInto(out *UpdateSpec) {
	*out = *in
}

// DeepCopy returns a deep copy of UpdateSpec.
func (in *UpdateSpec) DeepCopy() *UpdateSpec {
	if in == nil {
		return nil
	}
	out := new(UpdateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out.
func (in *ZaentrumSpec) DeepCopyInto(out *ZaentrumSpec) {
	*out = *in
	out.Identity = in.Identity
	in.Storage.DeepCopyInto(&out.Storage)
	out.Features = in.Features
	out.Update = in.Update
	if in.Replicas != nil {
		m := make(map[string]int32, len(in.Replicas))
		for k, v := range in.Replicas {
			m[k] = v
		}
		out.Replicas = m
	}
}

// DeepCopy returns a deep copy of ZaentrumSpec.
func (in *ZaentrumSpec) DeepCopy() *ZaentrumSpec {
	if in == nil {
		return nil
	}
	out := new(ZaentrumSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out.
func (in *ZaentrumStatus) DeepCopyInto(out *ZaentrumStatus) {
	*out = *in
	if in.Conditions != nil {
		l := make([]metav1.Condition, len(in.Conditions))
		for i := range in.Conditions {
			in.Conditions[i].DeepCopyInto(&l[i])
		}
		out.Conditions = l
	}
	if in.Components != nil {
		l := make([]ComponentStatus, len(in.Components))
		copy(l, in.Components)
		out.Components = l
	}
}

// DeepCopy returns a deep copy of ZaentrumStatus.
func (in *ZaentrumStatus) DeepCopy() *ZaentrumStatus {
	if in == nil {
		return nil
	}
	out := new(ZaentrumStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out.
func (in *Zaentrum) DeepCopyInto(out *Zaentrum) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy returns a deep copy of Zaentrum.
func (in *Zaentrum) DeepCopy() *Zaentrum {
	if in == nil {
		return nil
	}
	out := new(Zaentrum)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject returns a generically typed copy of Zaentrum.
func (in *Zaentrum) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies the receiver into out.
func (in *ZaentrumList) DeepCopyInto(out *ZaentrumList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		l := make([]Zaentrum, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&l[i])
		}
		out.Items = l
	}
}

// DeepCopy returns a deep copy of ZaentrumList.
func (in *ZaentrumList) DeepCopy() *ZaentrumList {
	if in == nil {
		return nil
	}
	out := new(ZaentrumList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject returns a generically typed copy of ZaentrumList.
func (in *ZaentrumList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
