apiVersion: zaentrum.io/v1alpha1
kind: Zaentrum
metadata:
  name: zaentrum
  namespace: zaentrum
spec:
  channel: stable
  version: latest
  hostname: zaentrum.localhost
  identity:
    mode: bundled
    clientId: chino-web
    audience: chino
  storage:
    mediaSize: 50Gi
  features:
    gpu: false
    kafka: true
  update:
    mode: manual
