apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: zaentrum-operator-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: zaentrum-operator-manager-role
subjects:
  - kind: ServiceAccount
    name: zaentrum-operator-controller-manager
    namespace: zaentrum-operator-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: zaentrum-operator-leader-election-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: zaentrum-operator-leader-election-role
subjects:
  - kind: ServiceAccount
    name: zaentrum-operator-controller-manager
    namespace: zaentrum-operator-system
